// Top travel destinations — city name → IATA metro/airport code
const CITY_TO_IATA = {
  // Southeast Asia
  'kuala lumpur': 'KUL', 'kl': 'KUL',
  'singapore': 'SIN',
  'bangkok': 'BKK',
  'phuket': 'HKT',
  'chiang mai': 'CNX',
  'jakarta': 'CGK',
  'bali': 'DPS', 'denpasar': 'DPS',
  'ho chi minh city': 'SGN', 'saigon': 'SGN',
  'hanoi': 'HAN',
  'da nang': 'DAD',
  'manila': 'MNL',
  'cebu': 'CEB',
  'yangon': 'RGN',
  'phnom penh': 'PNH',
  'siem reap': 'REP',
  'vientiane': 'VTE',
  'colombo': 'CMB',
  'kathmandu': 'KTM',
  // East Asia
  'tokyo': 'TYO',
  'osaka': 'OSA',
  'kyoto': 'UKY',
  'seoul': 'SEL',
  'busan': 'PUS',
  'beijing': 'BJS',
  'shanghai': 'SHA',
  'hong kong': 'HKG',
  'taipei': 'TPE',
  'macau': 'MFM',
  // South Asia
  'delhi': 'DEL', 'new delhi': 'DEL',
  'mumbai': 'BOM', 'bombay': 'BOM',
  'bangalore': 'BLR', 'bengaluru': 'BLR',
  'chennai': 'MAA',
  'hyderabad': 'HYD',
  'goa': 'GOI',
  'dhaka': 'DAC',
  'karachi': 'KHI',
  'lahore': 'LHE',
  // Middle East
  'dubai': 'DXB',
  'abu dhabi': 'AUH',
  'doha': 'DOH',
  'riyadh': 'RUH',
  'kuwait': 'KWI', 'kuwait city': 'KWI',
  'muscat': 'MCT',
  'beirut': 'BEY',
  'tel aviv': 'TLV',
  'amman': 'AMM',
  'istanbul': 'IST',
  // Europe
  'london': 'LON',
  'paris': 'PAR',
  'amsterdam': 'AMS',
  'frankfurt': 'FRA',
  'munich': 'MUC',
  'berlin': 'BER',
  'madrid': 'MAD',
  'barcelona': 'BCN',
  'rome': 'ROM',
  'milan': 'MIL',
  'venice': 'VCE',
  'florence': 'FLR',
  'naples': 'NAP',
  'vienna': 'VIE',
  'zurich': 'ZRH',
  'geneva': 'GVA',
  'brussels': 'BRU',
  'copenhagen': 'CPH',
  'oslo': 'OSL',
  'stockholm': 'STO',
  'helsinki': 'HEL',
  'lisbon': 'LIS',
  'porto': 'OPO',
  'athens': 'ATH',
  'prague': 'PRG',
  'warsaw': 'WAW',
  'budapest': 'BUD',
  'bucharest': 'OTP',
  'sofia': 'SOF',
  'zagreb': 'ZAG',
  'dubrovnik': 'DBV',
  'split': 'SPU',
  'reykjavik': 'REK',
  'edinburgh': 'EDI',
  'dublin': 'DUB',
  'nice': 'NCE',
  'lyon': 'LYS',
  'marseille': 'MRS',
  // Africa
  'cairo': 'CAI',
  'casablanca': 'CAS',
  'nairobi': 'NBO',
  'johannesburg': 'JNB',
  'cape town': 'CPT',
  'accra': 'ACC',
  'lagos': 'LOS',
  'addis ababa': 'ADD',
  'dar es salaam': 'DAR',
  'mauritius': 'MRU',
  // North America
  'new york': 'JFK', 'nyc': 'JFK',
  'los angeles': 'LAX', 'la': 'LAX',
  'miami': 'MIA',
  'chicago': 'CHI',
  'toronto': 'YYZ',
  'vancouver': 'YVR',
  'montreal': 'YUL',
  'san francisco': 'SFO',
  'las vegas': 'LAS',
  'seattle': 'SEA',
  'boston': 'BOS',
  'washington': 'WAS', 'washington dc': 'WAS',
  'dallas': 'DFW',
  'houston': 'IAH',
  'atlanta': 'ATL',
  'mexico city': 'MEX',
  'cancun': 'CUN',
  // South America & Caribbean
  'sao paulo': 'SAO',
  'rio de janeiro': 'RIO',
  'buenos aires': 'BUE',
  'bogota': 'BOG',
  'lima': 'LIM',
  'santiago': 'SCL',
  'havana': 'HAV',
  'san jose': 'SJO',
  // Oceania
  'sydney': 'SYD',
  'melbourne': 'MEL',
  'brisbane': 'BNE',
  'perth': 'PER',
  'auckland': 'AKL',
  'christchurch': 'CHC',
  'fiji': 'NAN', 'nadi': 'NAN',
  // Indian Ocean / Islands
  'maldives': 'MLE', 'male': 'MLE',
  'seychelles': 'SEZ',
  'zanzibar': 'ZNZ',
};

const IATA_TO_CITY = {
  'KUL': 'Kuala Lumpur', 'SIN': 'Singapore', 'BKK': 'Bangkok',
  'HKT': 'Phuket', 'CNX': 'Chiang Mai', 'CGK': 'Jakarta',
  'DPS': 'Bali', 'SGN': 'Ho Chi Minh City', 'HAN': 'Hanoi',
  'DAD': 'Da Nang', 'MNL': 'Manila', 'CEB': 'Cebu',
  'RGN': 'Yangon', 'PNH': 'Phnom Penh', 'REP': 'Siem Reap',
  'VTE': 'Vientiane', 'CMB': 'Colombo', 'KTM': 'Kathmandu',
  'TYO': 'Tokyo', 'OSA': 'Osaka', 'UKY': 'Kyoto',
  'SEL': 'Seoul', 'PUS': 'Busan', 'BJS': 'Beijing',
  'SHA': 'Shanghai', 'HKG': 'Hong Kong', 'TPE': 'Taipei', 'MFM': 'Macau',
  'DEL': 'Delhi', 'BOM': 'Mumbai', 'BLR': 'Bangalore',
  'MAA': 'Chennai', 'HYD': 'Hyderabad', 'GOI': 'Goa',
  'DAC': 'Dhaka', 'KHI': 'Karachi', 'LHE': 'Lahore',
  'DXB': 'Dubai', 'AUH': 'Abu Dhabi', 'DOH': 'Doha',
  'RUH': 'Riyadh', 'KWI': 'Kuwait City', 'MCT': 'Muscat',
  'BEY': 'Beirut', 'TLV': 'Tel Aviv', 'AMM': 'Amman', 'IST': 'Istanbul',
  'LON': 'London', 'PAR': 'Paris', 'AMS': 'Amsterdam',
  'FRA': 'Frankfurt', 'MUC': 'Munich', 'BER': 'Berlin',
  'MAD': 'Madrid', 'BCN': 'Barcelona', 'ROM': 'Rome', 'MIL': 'Milan',
  'VCE': 'Venice', 'FLR': 'Florence', 'NAP': 'Naples',
  'VIE': 'Vienna', 'ZRH': 'Zurich', 'GVA': 'Geneva', 'BRU': 'Brussels',
  'CPH': 'Copenhagen', 'OSL': 'Oslo', 'STO': 'Stockholm', 'HEL': 'Helsinki',
  'LIS': 'Lisbon', 'OPO': 'Porto', 'ATH': 'Athens', 'PRG': 'Prague',
  'WAW': 'Warsaw', 'BUD': 'Budapest', 'OTP': 'Bucharest',
  'SOF': 'Sofia', 'ZAG': 'Zagreb', 'DBV': 'Dubrovnik', 'SPU': 'Split',
  'REK': 'Reykjavik', 'EDI': 'Edinburgh', 'DUB': 'Dublin',
  'NCE': 'Nice', 'LYS': 'Lyon', 'MRS': 'Marseille',
  'CAI': 'Cairo', 'CAS': 'Casablanca', 'NBO': 'Nairobi',
  'JNB': 'Johannesburg', 'CPT': 'Cape Town', 'ACC': 'Accra',
  'LOS': 'Lagos', 'ADD': 'Addis Ababa', 'DAR': 'Dar es Salaam', 'MRU': 'Mauritius',
  'JFK': 'New York', 'LAX': 'Los Angeles', 'MIA': 'Miami',
  'CHI': 'Chicago', 'YYZ': 'Toronto', 'YVR': 'Vancouver', 'YUL': 'Montreal',
  'SFO': 'San Francisco', 'LAS': 'Las Vegas', 'SEA': 'Seattle',
  'BOS': 'Boston', 'WAS': 'Washington DC', 'DFW': 'Dallas', 'IAH': 'Houston',
  'ATL': 'Atlanta', 'MEX': 'Mexico City', 'CUN': 'Cancun',
  'SAO': 'São Paulo', 'RIO': 'Rio de Janeiro', 'BUE': 'Buenos Aires',
  'BOG': 'Bogotá', 'LIM': 'Lima', 'SCL': 'Santiago', 'HAV': 'Havana',
  'SJO': 'San José',
  'SYD': 'Sydney', 'MEL': 'Melbourne', 'BNE': 'Brisbane',
  'PER': 'Perth', 'AKL': 'Auckland', 'CHC': 'Christchurch', 'NAN': 'Fiji',
  'MLE': 'Maldives', 'SEZ': 'Seychelles', 'ZNZ': 'Zanzibar',
};

/**
 * Returns the IATA metro/airport code for a city name, or null if not found.
 * @param {string} city
 * @returns {string|null}
 */
export function cityToIata(city) {
  if (!city) return null;
  return CITY_TO_IATA[city.toLowerCase().trim()] ?? null;
}

/**
 * Returns the display city name for an IATA code, or null if not found.
 * @param {string} code
 * @returns {string|null}
 */
export function iataToCity(code) {
  if (!code) return null;
  return IATA_TO_CITY[code.toUpperCase().trim()] ?? null;
}
